// Code generated by "stringer -type=TokenType -trimprefix=TokenType_"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenType_LEFT_PAREN-0]
	_ = x[TokenType_RIGHT_PAREN-1]
	_ = x[TokenType_LEFT_BRACE-2]
	_ = x[TokenType_RIGHT_BRACE-3]
	_ = x[TokenType_COMMA-4]
	_ = x[TokenType_DOT-5]
	_ = x[TokenType_MINUS-6]
	_ = x[TokenType_PLUS-7]
	_ = x[TokenType_SEMICOLON-8]
	_ = x[TokenType_SLASH-9]
	_ = x[TokenType_STAR-10]
	_ = x[TokenType_BANG-11]
	_ = x[TokenType_BANG_EQUAL-12]
	_ = x[TokenType_EQUAL-13]
	_ = x[TokenType_EQUAL_EQUAL-14]
	_ = x[TokenType_GREATER-15]
	_ = x[TokenType_GREATER_EQUAL-16]
	_ = x[TokenType_LESS-17]
	_ = x[TokenType_LESS_EQUAL-18]
	_ = x[TokenType_IDENTIFIER-19]
	_ = x[TokenType_STRING-20]
	_ = x[TokenType_NUMBER-21]
	_ = x[TokenType_AND-22]
	_ = x[TokenType_CLASS-23]
	_ = x[TokenType_ELSE-24]
	_ = x[TokenType_FALSE-25]
	_ = x[TokenType_FOR-26]
	_ = x[TokenType_FUN-27]
	_ = x[TokenType_IF-28]
	_ = x[TokenType_NIL-29]
	_ = x[TokenType_OR-30]
	_ = x[TokenType_PRINT-31]
	_ = x[TokenType_RETURN-32]
	_ = x[TokenType_SUPER-33]
	_ = x[TokenType_THIS-34]
	_ = x[TokenType_TRUE-35]
	_ = x[TokenType_VAR-36]
	_ = x[TokenType_EOF-37]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFORFUNIFNILORPRINTRETURNSUPERTHISTRUEVAREOF"

var _TokenType_index = [...]uint8{0, 10, 21, 31, 42, 47, 50, 55, 59, 68, 73, 77, 81, 91, 96, 107, 114, 127, 131, 141, 151, 157, 163, 166, 171, 175, 180, 183, 186, 188, 191, 193, 198, 204, 209, 213, 217, 220, 223}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
